mysite/Event/urls.py
from django.conf.urls import url
from . import views

app_name = 'Event'


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/homepage/event-details
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'Event/add/$',views.EventCreate.as_view(), name='Event-add'),

    url(r'Event/(?P<pk>[0-9]+)/$', views.EventUpdate.as_view(), name='Event-update'),

    url(r'Event/(?P<pk>[0-9]+)/delete/$', views.EventDelete.as_view(), name='Event-delete'),

]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^',include('Event.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    """to check if debug is on """
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/Event/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse


class Event(models.Model):
    """incharge of creating of the events"""
    Event_title = models.CharField(max_length=200)
    Location = models.CharField(max_length=100)
    time = models.CharField(max_length=40)
    Event_type = models.CharField(max_length=300)
    Event_topic = models.CharField(max_length=250)
    ticket_type = models.CharField(max_length=200, default=False)
    Event_image = models.FileField(null=False, blank=False)
    Event_detail = models.CharField(max_length=1000)
    Organizer_name = models.CharField(max_length=100,null=False)
    updated = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False,auto_now_add=True)


    def get_absolute_url(self):
        """returns the detail page"""
        return reverse('Event:detail', kwargs={'pk':self.pk})


    def __unicode__(self):
        return self.Event_title

    def __str__(self):
        return self.Event_title

mysite/Event/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Event


class IndexView(generic.ListView):
    """incharge of returning the home page """
    template_name = 'Event/index.html'

    def get_queryset(self):
        """query the db to get a list of all the events"""
        return Event.objects.all()


class DetailView(generic.DetailView):
    """incharge of the events details"""
    model = Event
    template_name = 'Event/detail.html'


class EventCreate(CreateView):
    """creating a new event"""
    model = Event
    fields = ['Event_title', 'Location', 'time', 'Event_type', 'Event_topic', 'Event_image', 'Event_detail', 'Organizer_name']



class EventUpdate(UpdateView):
    """incharge of updating the Created event"""
    model = Event
    fields = ['Event_title', 'Location', 'time', 'Event_type', 'Event_topic', 'Event_image', 'Event_detail','Organizer_name']



class EventDelete(DeleteView):
    """incharge of deleting event"""
    model = Event
    success_url = reverse_lazy('Event:index')

mysite/Event/templates/Event/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no" />
    <meta name="author" content="">
    <meta name="description" content="Task">
    <meta name="keywords" content="">
    <title>The base page</title>
    <!-- loading th static files -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'Event/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'Event/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'Event/css/base.css' %}">
</head>
<body>

<!--========making of the navigation menu========== -->

<nav class="navbar navbar-default">
<div class="container-fluid">

    <!-- the logo & menu button section -->
    <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#topNavBar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#" class="navbar-brand">Events</a>
    </div>

<!--navigation items -->
<div class="collapse navbar-collapse" id="topNavBar">


    <form action="#" class="navbar-form navbar-left" role="search" method="get">
        <div class="form-group">
            <input type="text" class="form-control" name="q" value="">
        </div>
        <button type="submit" class="btn btn-success"> Search</button>
    </form>

<!-- the buttons on the right of the navbar -->
    <ul class="nav navbar-nav navbar-right">

        <li class="">
            <a href="#">
                <span class="glyphicon glyphicon-disk" aria-hidden="true"></span>&nbsp;Learn More
            </a>
        </li>

        <li class="">
            <a href="#">
                <span class="glyphicon glphicon-music" aria-hidden="true"></span>&nbsp;Browse Events
            </a>
        </li>

        <li class="">
            <a href="#">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Help
            </a>
        </li>

        <li class="">
            <a href="#">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;User
            </a>
        </li>

        <li class="">
            <a href="{% url 'Event:Event-add' %}">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;CREATE EVENT
            </a>
        </li>

    </ul>


</div>

</div>
</nav>
<body>

{% block content %}

{% endblock %}




<script src="{% static 'Event/js/jquery.js' %}"></script>
<script src="{% static 'Event/js/bootstrap.js' %}"></script>
<script src="{% static 'Event/js/base.js' %}"></script>
</body>
</html>

mysite/Event/templates/Event/detail.html
{% extends   'Event/base.html' %}
{% block title %} {{ Event }} {% endblock %}


{% block content %}

<div class="container-fluid">
<div class="row" id="eeeh">
    <div class="col-sm-6 col-md-6">
        <img src="{{ event.Event_image.url }}" alt="" class="img-responsive">
        title
        <h1>{{ event.Event_title }}</h1>
        type
        <h3>{{ event.Event_type }}</h3>
        Location
         <h3>{{ event.Location }}</h3>
        time
         <h3>{{ event.time }}</h3>

        <!--delete -->
        <form action="{% url 'Event:Event-delete' event.id %}" method="post" style="display: inline">
            {% csrf_token %}
            <input type="hidden" name="event_id" value="{{ event.id }}">
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>

         <a href="#"> CONTACT EVENT ORGANIZER</a> <br>


    <button> View MAp</button>


    </div>





</div><!--end of row-->


</div><!--end of container fluid ->




{% endblock %}

mysite/Event/templates/Event/event_form.html
{% block body %}
 <div class="container-fluid">
     <div class="row">

         <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                 <div class="panel-body">

                     <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'Event/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>

                     </form>
                     
                     
                     
                     
                     
                 </div>
             </div>

         </div>
     </div>


 </div>
{% endblock %}

mysite/Event/templates/Event/form-template.html
{% for field in form %}
<div class="form-group">
    <label class="control-label col-sm-2"> {{ field.label_tag }} </label>
    <div class="col-sm-10"> {{ field }} </div>


</div>

{% endfor %}

mysite/Event/templates/Event/index.html
{% extends 'Event/base.html' %}

{%  block content %}


<ul>
    {% for event in object_list %}
    <li><a href="{% url 'Event:detail' event.id %}"> {{ event.Event_title }}  </a> </li>

    {% endfor %}


</ul>

{% endblock %}